base/urls.py
from django.urls import path, include
# views folder
from .views import home, profile, room_messages, register_login, profile, rooms, forgot_pwd, guestest, convert, join_leave_room
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', home.home, name='home'),
    path('room/<str:pk>', room_messages.room, name='room'),
    path('create-room/', rooms.createRoom, name='create-room'),
    path('update-room/<str:pk>', rooms.updateRoom, name='update-room'),
    path('delete-room', rooms.deleteRoom, name='delete-room'),
    path('login/', register_login.LoginPage, name='login'),
    path('logout/', register_login.LogoutPage, name='logout'),
    path('register/', register_login.RegisterPage, name='register'),
    path('delete-msg', room_messages.deleteMessage, name='delete-msg'),
    path('edit-msg', room_messages.EditMessage, name='edit-msg'),
    path('profile/<str:pk>', profile.Profile, name='profile'),
    path('joined-rooms', profile.JoinedRooms, name='joined-rooms'),
    path('account', profile.AccountSettings, name='account'),
    path('forgot', forgot_pwd.ForgotPwd, name='forgot'),
    path("convert/", convert.custom_convert_form, name='guest_user_convert'),
    path('guest', guestest.welcome_user, name='guest_user_convert_success'),
    path('confirm_logout', guestest.ConfirmLogout, name="confirm-logout"),
    path('leave_room', rooms.LeaveRoom, name="leave-room"),
    path('join_room', rooms.JoinRoom, name="join-room"),
    path('invite/<str:code>', rooms.Invite, name='invite'),
    path('invite', rooms.InvitePage, name='invite-room'),
    path('join/<str:code>', rooms.InviteJoin, name='join'),
    path('load_messages', room_messages.LoadMessages, name='load-messages')

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

template_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.utils.text import slugify
import random
import string
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class UserProfile(models.Model):
    username = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(unique=True)
    bio = models.TextField(null=True, blank=True)

    pfp = models.ImageField(upload_to='images/',
                            default='/images/guest.webp')
    pfp_crop = ImageSpecField(source='pfp', processors=[
                              ResizeToFill(64, 64)], format='PNG', options={'quality': 60})

    def __str__(self):
        return self.email


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200, unique=True)
    participants = models.ManyToManyField(
        User, related_name='participants', blank=True)
    description = models.TextField(blank=True, null=True)
    private = models.BooleanField(default=False)

    invite_code = models.CharField(unique=True, max_length=6)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, blank=True)  # Add a SlugField

    def save(self, *args, **kwargs):
        # Generate a unique invite code
        if not self.invite_code:
            unique_code = self.generate_unique_invite_code()
            self.invite_code = unique_code

        # Generate and set the slug based on the name field
        if not self.slug:
            self.slug = slugify(self.name)

        super(Room, self).save(*args, **kwargs)

    def generate_unique_invite_code(self):
        # Generate a unique invite code
        while True:
            invite_code = ''.join(random.choice(
                string.ascii_letters + string.digits) for _ in range(6))
            if not Room.objects.filter(invite_code=invite_code).exists():
                return invite_code

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey('Room', on_delete=models.CASCADE)
    body = models.TextField()
    edited = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.body)[0:50]

base/views/convert.py
from guest_user.views import ConvertFormView
from ..forms import ProfileCreationForm
from ..models import UserProfile
from django.conf import settings as django_settings
from django.contrib.auth import REDIRECT_FIELD_NAME, authenticate, get_user_model, login
from django.contrib.auth.models import User
from django.shortcuts import redirect, resolve_url
from django.utils.http import url_has_allowed_host_and_scheme
from django.utils.module_loading import import_string
from django.views.generic import FormView, TemplateView
from django.shortcuts import render
from django.conf import settings
from guest_user.exceptions import NotGuestError
from guest_user.functions import get_guest_model, is_guest_user
from guest_user.mixins import GuestUserRequiredMixin


class CustomConvertFormView(GuestUserRequiredMixin, ConvertFormView):
    anonymous_url = "/login/"
    registered_url = "/"
    template_name = 'base/convert_guest.html'

    def get_success_url(self):
        return 'guest_user_convert_success'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        ProfileForm = ProfileCreationForm()
        context.update(
            {self.redirect_field_name: self.get_redirect_url(), 'ProfileForm': ProfileCreationForm})
        return context

    def form_valid(self, form):
        """Security check complete. Log the user in."""

        GuestModel = get_guest_model()

        profileForm = ProfileCreationForm(self.request.POST)
        if profileForm.is_valid():
            try:
                GuestModel.objects.convert(form)
            except NotGuestError:
                # Redirect if it's already a regular user.
                pass
            else:
                # Authenticate the user with standard backend.

                user = User.objects.get(
                    username=self.request.POST.get('username'))
                profile = UserProfile.objects.create(
                    username=user,
                    email=self.request.POST.get('email').lower(),
                )
                login(self.request, authenticate(
                    self.request, **form.get_credentials()))

                return redirect(self.get_success_url())

        context = super().get_context_data()
        context['ProfileForm'] = profileForm

        return render(self.request, template_name=self.template_name, context=context)


custom_convert_form = CustomConvertFormView.as_view()

base/views/forgot_pwd.py
from django.shortcuts import render, redirect
from ..models import Room, Topic, Message, UserProfile
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, JsonResponse
from django.db.models import Count
import random
import string
from django.contrib.auth import password_validation
from django.forms import ValidationError
from email.mime.text import MIMEText
from django.conf import settings
# Create your views here.
import smtplib


def send_email(to, subject, body):
    msg = MIMEText(body)
    msg['Subject'] = subject
    msg['To'] = to
    msg['From'] = settings.EMAIL_SENDER

    s = smtplib.SMTP(settings.MAIL_SERVER, settings.MAIL_PORT)
    s.starttls()
    s.login(settings.MAIL_USER, settings.MAIL_PWD)
    s.send_message(msg)
    s.quit()


def blur_email(email):
    if "@" in email:
        username, domain = email.split("@")
        # Keep the first and last characters
        username = username[:1] + "*" * (len(username) - 2) + username[-1]
        # Keep the first character
        domain = domain[:1] + "*" * (len(domain) - 1)
        return f"{username}@{domain}"
    else:
        return email


def ForgotPwd(request, backend='django.contrib.auth.backends.ModelBackend'):
    if request.session.get('code') and request.session.get('code_sucess'):
        type = 'changepwd'
        BlurEmail = None
    elif request.session.get('code'):
        type = "code"
        BlurEmail = blur_email(request.session.get('email'))
    else:
        type = "email"
        BlurEmail = None

    context = {'type': type, 'blur_email': BlurEmail}

    if request.GET.get('resend') == 'True':
        if request.session.get('code'):
            del request.session['code']
        if request.session.get('email'):
            del request.session['email']
        if request.session.get('code_sucess'):
            del request.session['code_sucess']

        return redirect('forgot')

    if request.method == 'POST':
        # enter email
        if not request.session.get('code') and not request.session.get('code_sucess'):
            uemail = request.POST.get('uemail')
            try:
                myemail = UserProfile.objects.get(
                    Q(username__username=uemail) | Q(email=uemail))
            except:
                messages.error(request, 'Email or username does not exist ')
                return render(request, 'base/forgot.html', context)
            else:
                # do stuff
                email = myemail.email

                characters = string.ascii_letters + string.digits
                six_character_code = ''.join(
                    random.choice(characters) for _ in range(6))

                send_email(email, 'Verification Code', f"""
                YOUR VERIFICATION CODE IS {six_character_code}""")

                request.session['code'] = six_character_code
                request.session['email'] = email

                return redirect('forgot')

        # enter code
        elif request.session.get('code') and not request.session.get('code_sucess'):
            code = request.POST.get('code')
            if code == request.session['code']:
                request.session['code_sucess'] = True
                return redirect('forgot')
            else:
                messages.error(request, 'Wrong Code')
        # change pwd
        elif request.session.get('code') and request.session.get('code_sucess'):
            pwd = request.POST.get('password1')
            re_pwd = request.POST.get('password2')

            if pwd != re_pwd:
                messages.error(request, 'Passwords do not match ')
            else:
                try:
                    password_validation.validate_password(pwd)
                except ValidationError as e:
                    messages.error(request, e)
                else:
                    myuser = UserProfile.objects.get(
                        email=request.session.get('email')).username

                    user = User.objects.get(username=myuser)
                    user.set_password(pwd)
                    user.save()
                    login(request, user, backend=backend)
                    return redirect('home')

    return render(request, 'base/forgot.html', context)

base/views/guestest.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from ..models import Room
from django.db.models import Q
from django.db.models import Count
from guest_user.decorators import allow_guest_user, guest_user_required


@allow_guest_user
def welcome_user(request):
    next = 'home' if not request.GET.get('next') else request.GET.get('next')

    return redirect(next)


@guest_user_required
def ConfirmLogout(request):
    return render(request, 'base/confirm_logout.html', {})

base/views/home.py
from django.shortcuts import render, redirect
from ..models import Room, UserProfile
from django.db.models import Q
from django.db.models import Count
from guest_user.decorators import allow_guest_user
from django.conf import settings
# Create your views here.


def home(request):

    q = request.GET.get('q') if request.GET.get('q') else ''
    topics_only = request.GET.get(
        'topic') if request.GET.get('q') else ''
    page = int(request.GET.get('page')) if request.GET.get('page') else 1

    order_by = '-updated' if request.GET.get(
        'filter') == 'recent' else 'participants'

    rooms = Room.objects.filter().order_by(order_by)

    one_page = settings.ROOM_PAGE
    end_page = page * one_page
    start_page = end_page - one_page

    if topics_only:
        rooms = rooms.filter(
            Q(topic__name__icontains=q)
        )

    else:
        rooms = rooms.filter(
            Q(topic__name__icontains=q) |
            Q(name__icontains=q) |
            Q(description__icontains=q)
        )

    if request.user.is_authenticated:
        rooms = rooms.filter(Q(private=False) | Q(
            participants=int(request.user.id)))
    else:
        rooms = rooms.filter(private=False)

    rooms = list(dict.fromkeys(rooms))
    room_count = len(rooms)

    rooms = rooms[start_page:end_page]
    last_page = room_count//one_page + (room_count % one_page > 0)

    context = {'rooms': rooms,
               'q': q, 'topics_only': topics_only, 'room_count': room_count, 'last_page': last_page}

    return render(request, 'base/home.html', context)

base/views/join_leave_room.py
from django.shortcuts import render, redirect
from ..models import Room, Topic, Message
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, JsonResponse
from django.db.models import Count
from guest_user.functions import is_guest_user
# Create your views here.


@login_required
def JoinRoom(request):
    pass


@login_required
def LeaveRoom(request):
    pass

base/views/register_login.py
from django.shortcuts import render, redirect
from ..models import Room, Topic, Message, UserProfile
from ..forms import RoomForm, ProfileCreationForm
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, JsonResponse
from django.db.models import Count
# Create your views here.


def LoginPage(request, backend='django.contrib.auth.backends.ModelBackend'):
    page = 'login'
    context = {'page': page}
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        context = {'page': page, 'username': username, 'password': password}
        try:
            user = User.objects.get(username=username)
        except:
            try:
                user = UserProfile.objects.get(email=username)
                username = user.username
            except:
                messages.error(request, 'Username or Email does not exist')
                return render(request, 'base/register_login.html', context)

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user, backend=backend)
            return redirect('home')
        else:
            messages.error(request, 'Wrong Password')

    return render(request, 'base/register_login.html', context)


def RegisterPage(request, backend='django.contrib.auth.backends.ModelBackend'):
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        UserForm = UserCreationForm(request.POST)
        ProfileForm = ProfileCreationForm(request.POST)

        if ProfileForm.is_valid() and UserForm.is_valid():
            user = UserForm.save(commit=False)
            user.username = user.username.lower()
            user.save()

            profile = UserProfile.objects.create(
                username=user,
                email=request.POST.get('email').lower(),
            )

            login(request, user, backend=backend)
            return redirect('home')

    else:
        UserForm = UserCreationForm()
        ProfileForm = ProfileCreationForm()

    context = {'UserForm': UserForm, 'ProfileForm': ProfileForm}
    return render(request, 'base/register_login.html', context)


@login_required(login_url='login')
def LogoutPage(request):
    logout(request)
    return redirect('home')

base/templates/base/components/activity.html
<div class="md:col-span-3 col-span-0 hidden md:block my-10 z-10 ">
    <div class="fixed lg:w-64 xl:w-[20rem]">

        <h2 class="text-center text-xl font-semibold ">Recent Activities</h2>
        <hr class=" border-primary-glow-green border-[-.5px] opacity-50 mb-4">

        {%for message in info.room_messages %}
        <small class="text-xs text-gray-400"><a href="{% url 'profile' message.user %}">@{{message.user}}</a>
            {{message.updated|timesince}} ago in
            <a class="text-blue-400" href="{%url 'room' message.room.id %}">{{message.room.name}}</a></small>
        <div class="text-xs dark:bg-gray-900 bg-gray-200 p-2 rounded mr-4 break-words">
            {{message.body}}
        </div>
        <hr class=" border-primary-glow-green border-[-.5px] opacity-50 my-3">

        {%endfor%}
    </div>
</div>

base/templates/base/components/modals.html
<!-- Small Modal for search -->
<div id="small-modal" tabindex="-1"
    class="blur-modal fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->

            <!-- Modal body -->
            <div class="">
                <form action="#" method="get">
                    <input type="text" name="q"
                        class=" border border-green-300 border-l-0 border-t-0 border-r-0  border-b-4 text-gray-900 sm:text-sm  focus:ring-primary-500 focus:border-primary-500 block w-full pl-10 p-2.5 dark:bg-gray-700  dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                        placeholder="Search for Rooms">
                </form>
            </div>
            <!-- Modal footer -->

        </div>
    </div>
</div>





<!-- Large Modal  for topics -->
<div id="large-modal" tabindex="-1"
    class="blur-modal fixed top-0 left-0 right-0 z-[102] hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative w-full max-w-4xl max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-5 border-b rounded-t dark:border-gray-600">
                <h3 class="text-3xl text-center font-medium text-gray-900 dark:text-white">
                    All Topics
                </h3>
                <button type="button"
                    class="modal-close text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white"
                    data-modal-hide="large-modal">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                        viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-6 space-y-6">
                <hr class=" border-primary-glow-green border-[-.5px] opacity-50">

                {%for topic in info.topics%}
                <a href="/?q={{topic}}&topic=True">
                    <div class="flex justify-between">

                        <div class="mx-10 mt-5 text-xl font-semibold">
                            {{topic}}

                        </div>
                        <div class="bg-green-400 rounded-2xl mt-5 text-xs font-thin text-gray-300 p-2 self-center ml-1">
                            {{topic.room_set.all.count}}
                        </div>
                    </div>
                </a>

                <hr class=" border-primary-glow-green border-[-.5px] opacity-50">

                {%endfor%}
            </div>

        </div>
    </div>
</div>


<!-- modal for deleting rooms -->
<div id="small-modal1" tabindex="-1"
    class="blur-modal fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-5 border-b rounded-t dark:border-gray-600">
                <h3 class="text-2xl text-center font-semibold text-gray-900 dark:text-white">
                    Delete Room
                </h3>
                <button type="button"
                    class="modal-close text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white"
                    data-modal-hide="small-modal1">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                        viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-6 space-y-6">
                Are you sure you want to delete <span class="font-extrabold" id="room-name"></span> room?
            </div>
            <!-- Modal footer -->
            <div class="flex items-center p-6 space-x-2 border-t border-gray-200 rounded-b dark:border-gray-600">
                <button data-modal-hide="small-modal1" id="confirm-delete-btn" type="button"
                    class="modal-close text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800">Delete</button>


                <button data-modal-hide="small-modal1" type="button"
                    class="modal-close text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">Cancel</button>
            </div>
        </div>
    </div>
</div>


<!-- singup / guest modal -->
<!-- Default Modal -->
<div id="signup-modal" tabindex="-1"
    class="blur-modal fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative w-full max-w-lg max-h-full">
        <!-- Modal content -->
        <div class="relative text-white bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal body -->
            <div>&nbsp;</div>
            <div class="mx-10 my-5">
                <a href="{%url 'register'%}">
                    <button class="block w-full p-5 bg-green-400 text-xl font-semibold">Signup/Login with Email</button>
                </a>

                <a href="/guest">
                    <button class="my-4  block w-full p-5 bg-gray-800">
                        <p class="text-xl font-semibold">Sign in as Guest</p>
                        <p class="text-xs font-extralight">nothing required</p>
                    </button>
                </a>
            </div>
            <a data-modal-hide="signup-modal" class="dark:text-gray-400 text-gray-800 modal-close hover:cursor-pointer">
                <div class="opacity-90 text-center text-xs font-extrabold">maybe later</div>
            </a>
            <div>&nbsp;</div>
        </div>
    </div>
</div>



<!-- leave room -->
<!-- modal for deleting rooms -->
<div id="leave-room" tabindex="-1"
    class="blur-modal fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-5 border-b rounded-t dark:border-gray-600">
                <h3 class="text-2xl text-center font-semibold text-gray-900 dark:text-white">
                    Leave Room
                </h3>
                <button type="button"
                    class="modal-close text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white"
                    data-modal-hide="leave-room">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                        viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-6 space-y-6">
                Are you sure you want to leave <span class="font-extrabold" id="room-name-leave"></span>?
            </div>
            <!-- Modal footer -->
            <div class="flex items-center p-6 space-x-2 border-t border-gray-200 rounded-b dark:border-gray-600">
                <a href="{%url 'leave-room'%}?id={{room.id}}"> <button data-modal-hide="leave-room" type="button"
                        id="room-leave-btn"
                        class="modal-close text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800">Leave</button>
                </a>


                <button data-modal-hide="leave-room" type="button"
                    class="modal-close text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">Cancel</button>
            </div>
        </div>
    </div>
</div>



<!-- delete msg -->
<div id="deleteMsg" tabindex="-1"
    class="fixed top-0 left-0 right-0 z-50 hidden p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative w-full max-w-md max-h-full">
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <button type="button"
                class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white"
                data-modal-hide="deleteMsg">
                <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                    viewBox="0 0 14 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                </svg>
                <span class="sr-only">Close modal</span>
            </button>
            <div class="p-6 text-center">
                <svg class="mx-auto mb-4 text-gray-400 w-12 h-12 dark:text-gray-200" aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                </svg>
                <h3 class="mb-5 text-lg font-normal text-gray-500 dark:text-gray-400">Are you sure you want to delete
                    this message?</h3>
                <p id="msg-txt-modal"
                    class="dark:bg-gray-800 bg-gray-200 rounded text-sm font-extralight p-3 shadow-2xl mb-4 break-words">
                </p>

                <button id="delete-btn-confirm" data-modal-hide="deleteMsg" type="button"
                    class="text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center mr-2">
                    Yes, I'm sure
                </button>
                <button data-modal-hide="deleteMsg" type="button"
                    class="text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">No,
                    cancel</button>
            </div>
        </div>
    </div>
</div>